/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"

int *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	struct timeval t;
	
	gettimeofday(&t, NULL);
	printf("Now : %d\n", (int)t.tv_sec);

	result = (int)t.tv_sec - tod;
//	result = (int)t.tv_sec;

	return &result;
}

void *
delay_time_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	pthread_mutex_t mutex=PTHREAD_MUTEX_INITIALIZER;

	pthread_mutex_lock(&mutex);

	printf("Delayed %d sec\n", *argp);
	tod+=*argp;
	
	pthread_mutex_unlock(&mutex);

	return (void *) &result;
}
