/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"

void
time_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *get_time_1_arg;
	void  *result_2;
	int  delay_time_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Time_PROG, Time_Vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_time_1((void*)&get_time_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = delay_time_1(&delay_time_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void delay_func(void *args){
	int ran;
	pthread_mutex_t mut=PTHREAD_MUTEX_INITIALIZER;

	pthread_mutex_lock(&mut);
	srand(time(NULL));
	ran=rand()%10;

	if( delay_time_1(&ran, (CLIENT*)args) == NULL )
		clnt_perror((CLIENT*)args, "delay failed");

	printf("delay %d sec\n", ran);

	pthread_mutex_unlock(&mut);
}

int
main (int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;
	int *time, delay, status, N, i;
	void *result2;
	char *args;
	pthread_t thrds[100];

	if (argc < 3) {
		printf ("usage: %s server_host threads#\n", argv[0]);
		exit (1);
	}
//	host = argv[1];
//	time_prog_1 (host);
	N = atoi(argv[2]);

	clnt = clnt_create(argv[1], Time_PROG, Time_Vers, "udp");
	if(clnt == NULL){
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	time = get_time_1((void*)&args, clnt);
	if(time==NULL){
		clnt_perror(clnt, "get failed");
	}
	printf("Elapsed Server Time: %d\n", *time);

	for( i=0; i<N; i++)
		pthread_create(&thrds[i], NULL, &delay_func,(void*)clnt);
	
//	result2 = delay_time_1(&delay, clnt);
//	if(time==NULL){
//		clnt_perror(clnt, "delay failed");
//	}

	for(i=0; i<N; i++)
		pthread_join(thrds[i], (void**)&status);

	time = get_time_1((void*)&args, clnt);
	if(time==NULL){
		clnt_perror(clnt, "get failed");
	}
	printf("Elapsed Server Time: %d\n", *time);
	
	clnt_destroy(clnt);

	exit (0);
}
